import Box from "@mui/material/Box";
import { GridColDef } from "@mui/x-data-grid";
import { Avatar, Typography } from "@mui/material";
import {
  user,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  user10,
  user11,
  user12,
  user13,
  user14,
  user15,
  user16,
  user17,
  user18,
  user19,
  user20,
  user21,
  user22,
  user23,
  user24,
} from "../../assets/users/userImg";

export const columns: GridColDef[] = [
  {
    field: "avatar",
    headerName: "Avatar",
    width: 80,
    renderCell: (params) => {
      return (
        <>
          <Avatar src={params.value} alt="avatar"></Avatar>
        </>
      );
    },
    sortable: false,
  },
  {
    field: "username",
    headerName: "Name",
    minWidth: 160,
    flex: 1,
    renderCell: (params) => {
      return <Typography fontWeight={"semi-bold"}>{params.value}</Typography>;
    },
  },
  {
    field: "company",
    headerName: "Company",
    minWidth: 180,
    flex: 1,
  },
  { field: "role", headerName: "Role", minWidth: 160, flex: 1 },
  {
    field: "verified",
    headerName: "Verified",
    minWidth: 100,
  },
  {
    field: "status",
    headerName: "Status",
    flex: 1,
    minWidth: 100,
    renderCell: (params) => {
      return (
        <Box
          sx={{
            backgroundColor:
              params.value == "Banned" ? "#ff563029" : "#00a76f29",
            color: params.value == "Banned" ? "#b71d18" : "#007867",
            padding: "0.2rem 0.4rem",
            fontSize: 12,
            fontWeight: "medium",
            borderRadius: 2,
          }}>
          {params.value}
        </Box>
      );
    },
  },
];

export const rows = [
  {
    id: 1,
    username: "Cersei Lannister",
    avatar: user2,
    company: "Predovic - Glover",
    role: "UI/UX Designer",
    verified: "Yes",
    status: "Banned",
  },
  {
    id: 2,
    username: "Arya Stark",
    avatar: user4,
    company: "Herman and Sons",
    role: "UI Designer",
    verified: "Yes",
    status: "Banned",
  },
  {
    id: 3,
    username: "Daenerys Targaryen",
    avatar: user5,
    company: "	Weissnat Group",
    role: "UI Designer",
    verified: "No",
    status: "Banned",
  },

  {
    id: 4,
    username: "Gerard Bogisich",
    avatar: user6,
    company: "Considine - Runte",
    role: "Hr Manager",
    verified: "Yes",
    status: "Active",
  },
  {
    id: 5,
    username: "Jennifer Botsford",
    avatar: user7,
    company: "Yost, Labadie and Gleichner",
    role: "	UX Designer",
    verified: "No",
    status: "Active",
  },
  {
    id: 6,
    username: "Homer Borer DDS",
    avatar: user8,
    company: "Upton LLC",
    role: "	Front End Developer",
    verified: "No",
    status: "Banned",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar: user,
    company: "Nikolaus - Rogahn",
    role: "UI/UX Designer",
    verified: "No",
    status: "Banned",
  },
  {
    id: 8,
    username: "Jaime Lannister",
    avatar: user3,
    company: "Nikolaus - Davis",
    role: "Project Manager",
    verified: "No",
    status: "Active",
  },
  {
    id: 9,
    username: "Ignacio Becker DVM",
    avatar: user9,
    company: "Leuschke - McClure",
    role: "Full Stack Designer",
    verified: "No",
    status: "Banned",
  },
  {
    id: 10,
    username: "Jeff Purdy",
    avatar: user10,
    company: "	Bins Inc",
    role: "	Leader",
    verified: "No",
    status: "Active",
  },
  {
    id: 11,
    username: "Dr. Camille Satterfield",
    avatar: user11,
    company: "Keeling - Turner",
    role: "UX Designer",
    verified: "No",
    status: "Active",
  },
  {
    id: 12,
    username: "Denise Hammes",
    avatar: user12,
    company: "Padberg, Wolf and Bednar",
    role: "UI Designer",
    verified: "No",
    status: "Active",
  },
  {
    id: 13,
    username: "Brian Gutmann",
    avatar: user13,
    company: "Abbott LLC",
    role: "Backend Developer",
    verified: "No",
    status: "Active",
  },
  {
    id: 14,
    username: "Antonia Altenwerth II",
    avatar: user14,
    company: "Ullrich and Sons",
    role: "Full Stack Developer",
    verified: "Yes",
    status: "Active",
  },
  {
    id: 15,
    username: "Alexander Miller",
    avatar: user15,
    company: "Medhurst, Hilll and Tromp",
    role: "		Hr Manager",
    verified: "No",
    status: "Active",
  },
  {
    id: 16,
    username: "Mr. Darin Schumm",
    avatar: user16,
    company: "Pagac and Sons",
    role: "Hr Manager",
    verified: "Yes",
    status: "Active",
  },
  {
    id: 17,
    username: "Melissa Gulgowski",
    avatar: user17,
    company: "Kohler - Batz",
    role: "UX Designer",
    verified: "Yes",
    status: "Banned",
  },
  {
    id: 18,
    username: "Melba Ortiz",
    avatar: user18,
    company: "Green, Watsica and Lang",
    role: "Hr Manager",
    verified: "No",
    status: "Active",
  },
  {
    id: 19,
    username: "Karl Jacobs I",
    avatar: user19,
    company: "Larkin - O'Connell",
    role: "	Project Manager",
    verified: "No",
    status: "Active",
  },
  {
    id: 20,
    username: "Jesus Denesik PhD",
    avatar: user20,
    company: "Kub LLC",
    role: "			Project Manager",
    verified: "No",
    status: "Banned",
  },
  {
    id: 21,
    username: "Drew Turcotte III",
    avatar: user21,
    company: "Little LLC",
    role: "Full Stack Developer",
    verified: "Yes",
    status: "Banned",
  },
  {
    id: 22,
    username: "Ebony Bins",
    avatar: user22,
    company: "Heathcote, Bergstrom and Raynor",
    role: "	Hr Manager",
    verified: "No",
    status: "Active",
  },
  {
    id: 23,
    username: "Harold Anderson",
    avatar: user23,
    company: "Shanahan, Weber and Green",
    role: "	Backend Developer",
    verified: "No",
    status: "Banned",
  },
  {
    id: 24,
    username: "Ivan Jenkins",
    avatar: user24,
    company: "Goodwin LLC",
    role: "UI Designer",
    verified: "Yes",
    status: "Active",
  },
];
